### ISSUE TITLE
About network parameter setting

### ISSUE THREAD

**Issue by deartonym** [akanimax/pro_gan_pytorch#1]
Hi,
I see that there are some parameter settings which are some sort of different from the original paper, e.g., the latent_size is set as 128 throughout the whole G and D networks. However in the original paper, it increases/decreases from 16 to 512 or vice versa. Is there any specific reason that this implementation has such different setting? Or just for simplification with limited performance influence?

Thanks!

**Comment by akanimax** [comment]
Hi @deartonym,

I have made the number channels (i.e. the network size) a function of `latent_size` and `depth`. If you are encountering same number of channels for all layers, then perhaps your `depth <= 4`. If you wish to have an architecture same as that mentioned in the paper, please use the values: `depth=9` and `latent_size=512`. You could just change the config values in the [config_file](https://github.com/akanimax/pro_gan_pytorch-examples/blob/master/implementation/configs/lfw.conf) in the published examples for this package. 

BTW, I created an architecture which bypasses the whole complicated progressive training (thereby has much less hyperparameters) called [MSG-GAN](https://github.com/akanimax/MSG-GAN). **MSG-GAN** is also able to generate images at **[1024 x 1024]** resolution. Do check it out :smile:.

I hope this helps

Cheers :beers:!
@akanimax

**Comment by deartonym** [comment]
> Hi @deartonym,
> 
> I have made the number channels (i.e. the network size) a function of `latent_size` and `depth`. If you are encountering same number of channels for all layers, then perhaps your `depth <= 4`. If you wish to have an architecture same as that mentioned in the paper, please use the values: `depth=9` and `latent_size=512`. You could just change the config values in the [config_file](https://github.com/akanimax/pro_gan_pytorch-examples/blob/master/implementation/configs/lfw.conf) in the published examples for this package.
> 
> BTW, I created an architecture which bypasses the whole complicated progressive training (thereby has much less hyperparameters) called [MSG-GAN](https://github.com/akanimax/MSG-GAN). **MSG-GAN** is also able to generate images at **[1024 x 1024]** resolution. Do check it out smile.
> 
> I hope this helps
> 
> Cheers beers!
> @akanimax

Thanks for your explanation! I will go and check MSG-GAN.

**Comment by deartonym** [comment]
@akanimax 
Thanks again!
The layers and parameters are exactly as described in the paper!
