### ISSUE TITLE
Mnist dataset

### ISSUE THREAD

**Issue by orrimoch** [akanimax/pro_gan_pytorch#24]
Where to download the Mnist dataset?
Is it should be the normal CSV (28x28) dataset?

Thanks,
Or

**Comment by akanimax** [comment]
Hi @orrimoch, sorry for the late reply.
Oh you need the image version of the MNIST dataset. You can find one here -> https://www.kaggle.com/scolianni/mnistasjpg

**Comment by akanimax** [comment]
@orrimoch 

Hope this is resolved. 
Please feel free to reopen if you need any help.

Best regards,
@akanimax
