### ISSUE TITLE
Pretrained models for lower resolutions

### ISSUE THREAD

**Issue by wsgharvey** [akanimax/pro_gan_pytorch#25]
Great results! Is there any chance you could provide the pretrained weights for the lower-resolution versions of CelebA-HQ? (in particular, I'm keen to see the 256x256 version)

Thanks,
Will

**Comment by akanimax** [comment]
@wsgharvey, 
Sorry for the late reply. If you still need the model, please let me know your email id, I'll share the final (model at the completion of this layer of training) 256_x_256 model with you. 
Best regards,
@akanimax

**Comment by akanimax** [comment]
@wsgharvey,

Hope you have obtained lower res models till now. 
Please feel free to reopen in case you need any help.

Best regards,
@akanimax

**Comment by guuske31** [comment]
Hello @akanimax , 

I was wondering if you still have that pretrained model for 256x256 resolution model?
I would like to use it in my research.

Kind Regards,
Guus
