### ISSUE TITLE
Greyscale modifications?

### ISSUE THREAD

**Issue by msmacpherson** [akanimax/pro_gan_pytorch#28]
Hi Akanimax!
Thanks for providing this code.  I'm a pytorch beginner trying to use your code for an undergrad project.  I'm trying to use your implementation with a greyscale single channel dataset (ie same format as mnist), but get an error because the network expects 3-channel inputs.  Should I transform my data to 3-channel first, or is there a way to toggle to single channel in the code?  I assume that would make training much faster.

Sorry for a basic question for you.
Matthew

**Comment by akanimax** [comment]
@msmacpherson,
Sorry, you are right. Currently, there is no way for changing the number of channels of the output generated images. In case of MNIST, I did the same things (replicating the channels thrice). You could either do this (works pretty well), or change a little bit of code to include single channel images as well. Please feel free to open a PR here if you do implement it. 

In my case, I was going to do it, but procrastination got in the way ... you know :laughing:. Besides, colour images are more fun you know :smile:.

Glad that this repo is helpful for you.

Cheers :beers:!
@akanimax

**Comment by msmacpherson** [comment]
Thanks a lot!  I'm spending my whole life trying to make tensors match up at the moment.  If you don't mind I also found an error when i run the ProGan (unconditional mode) with cifar10 (I just removed classes from the command line to run using your code otherwise):

pro_gan = pg.ProGAN(depth=depth, 
                                   latent_size=latent_size, device=device)

Which gives me this error:

Files already downloaded and verified
Starting the training process ... 


Currently working on Depth:  0
Current resolution: 4 x 4

Epoch: 1
Traceback (most recent call last):

  File "<ipython-input-3-ed2bd1761d93>", line 62, in <module>
    batch_sizes=batch_sizes

  File "/home/matt/MSC/Progan/pro_gan_pytorch/PRO_GAN.py", line 607, in train
    images = batch.to(self.device)

AttributeError: 'list' object has no attribute 'to'

Is there an additional preprocessing required for unconditional training please?  For my project I'm looking at single class x-ray images initially so I only have a single image class.
