### ISSUE TITLE
Is multi-GPU supported?

### ISSUE THREAD

**Issue by deartonym** [akanimax/pro_gan_pytorch#3]
As the title.
Is it easy to expand this code to multigpu support by applying `nn.DataParallel` to all network forwards?

Best,

**Comment by deartonym** [comment]
I tried some attempts.
1. Carefully revise the forward() parts for both Discriminator and Generator. Note that the forward() parts are actually some sort of complicated, since the model is not a straight style (with diverging and combining operations).

2. Try to use simple coding style:
```
            self.gen = th.nn.DataParallel(self.gen)
            self.gen.to(device=th.device("cuda:0"))
```

1. works. 
2. The program will break down with problem of EMA:

```
Traceback (most recent call last):
  File "../run_example.py", line 86, in <module>
    gen_loss = pro_gan.optimize_generator(noise, current_depth, alpha)
  File "../PRO_GAN.py", line 504, in optimize_generator
    self.__apply_ema_on_generator()
  File "../PRO_GAN.py", line 410, in __apply_ema_on_generator
    param.data = self.ema(name, param.data)
  File "/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "../pro_gan_pytorch/CustomLayers.py", line 247, in forward
    assert name in self.shadow
```

Do you have any suggestions for the multi-gpu extension?

Since the forwarding part is complicated, I prefer to make 2. work.

Thank you!

**Comment by akanimax** [comment]
@deartonym,

Thank you for the issue. I have added multi-gpu support in [ad51fc3da9cd352c43a362652627e177d0887152](https://github.com/akanimax/pro_gan_pytorch/commit/ad51fc3da9cd352c43a362652627e177d0887152)
Latest version no. for the package is **`1.3.3`**. Try it and let me know if you face any issues.

Cheers :beers:!
@akanimax

**Comment by deartonym** [comment]
Thanks!
