### ISSUE TITLE
Some questions about generating face samples( using pre-trained model)

### ISSUE THREAD

**Issue by jackchen03** [akanimax/pro_gan_pytorch#30]
First of all, thank you for this pytorch implementation and this whole package, it is truly amazing!
However, I don't know if I use the pretrained model in the correct way. 
I tried to generate some image samples using "generate samples.py", and the generator model is loaded from saved_models/best_model/GAN_GEN_SHADOW_8.pth.
I just ran the script and generate 300 image samples, but the color of the image is somewhat strange, but I don't know how to fix it. Maybe I did this in the wrong way.
However, I also ran "demo.py", and the demo result is pretty good. The generator model is loaded from the same path, and thus I don't know what made this difference. 
I attach some of the generated image samples below. 

![97](https://user-images.githubusercontent.com/46782913/62193254-fe5f1580-b3a9-11e9-9c59-2632e862524f.png)
![77](https://user-images.githubusercontent.com/46782913/62193267-03bc6000-b3aa-11e9-8976-fb67c12fd491.png)
![64](https://user-images.githubusercontent.com/46782913/62193275-061eba00-b3aa-11e9-8233-9f5a152b14fc.png)

**Comment by akanimax** [comment]
@jackchen03,

I am glad that you find the package helpful.
Please check the default value of the `--out_depth` parameter in the `generate_samples.py` script [here](https://github.com/akanimax/pro_gan_pytorch/blob/master/samples/generate_samples.py#L40).
If you are running the script with this default value, you are basically generating samples from a previous layer. Please set it to 8 to get the `1024 x 1024` resolution samples. The demo does this automatically. 

We found it really counter-intuitive that the images generated from lower layers of a fully trained progressive GAN have such different colours. So, the same is also pointed out in our paper MSG-GAN. [see figure 3.](https://arxiv.org/pdf/1903.06048.pdf)
Please feel free to read the paper for more information.

Hope this helps.

Cheers :beers:!
@akanimax

**Comment by jackchen03** [comment]
It worked! Thanks for your quick reply and help!

**Comment by akanimax** [comment]
Closing the issue now :smile: 
Please feel free to reopen if you have any problem
