### ISSUE TITLE
How do I get celebA-HQ data?

### ISSUE THREAD

**Issue by vgunjal** [akanimax/pro_gan_pytorch#38]
I assume that for training and getting the quality of results that you have listed, you have used the celebA-HQ dataset. May I know how to generated the 1024x1024 images? I know the original authors provide a way to generate deltas, but I'm not sure how these are used to generate the 1024x1024 images.

I tried using https://github.com/nperraud/download-celebA-HQ , but that script no longer works. Sorry, I know that this is not directly related to your repo, but I can't figure out what to do next. 

EDIT: Related question, I saw that many references to the celebA-HQ data mention 128x128, 256x256 & 512x512 versions as well. Are these required when training my own version of ProGAN?

**Comment by earsonlau** [comment]
may I ask you have you solved this?
