### ISSUE TITLE
recalucating of __progressive_downsampling

### ISSUE THREAD

**Issue by joelive** [akanimax/pro_gan_pytorch#40]
It's strange that both optimize_discriminator and optimize_generator call __progressive_downsampling to downsample realimage. Why not downsample the realimage zhen pass it to optimize_discriminator and optimize_generator?

**Comment by akanimax** [comment]
@joelive, 
indeed, it seems redundant at first, but I designed it this way to allow the user of the package to create her own implementation of the training schedule. The `train` method that ships with the package is a very simple and basic version. For instance, with the relativistic losses, resampling the real images for the generator and discriminator passes is crucial to avoid mode collapse. 
Please feel free to submit a PR if you have a better design. 
Hope this helps.

Cheers :beers:!
@akanimax
