### ISSUE TITLE
no module name pro_gan_pytorch.PRO_GAN

### ISSUE THREAD

**Issue by qzj19951231** [akanimax/pro_gan_pytorch#49]
sorrry, i meetting this issue: no module name pro_gan_pytorch.PRO_GAN,i follow your code step by step,  such as pip install pro_gan_pytorch and ... .

**Comment by akanimax** [comment]
The api has changed completely since `v3.0`. Please take a look at the `pro_gan_pytorch_scripts/` for examples on how to use the package.
