### ISSUE TITLE
256x256 pretrained model

### ISSUE THREAD

**Issue by guuske31** [akanimax/pro_gan_pytorch#51]
Hello @akanimax ,

Because I couldn't reopen issue: https://github.com/akanimax/pro_gan_pytorch/issues/25
I was wondering if you could provide me with pretrained model for the discriminator and generator with the resolution of 256x256 on the CelebA-HQ dataset. It would really improve my research.\

Kind Regards,
Guus

**Comment by akanimax** [comment]
Hi @guuske31, 
I know it's super late, I am figuring out some compute logistics from my end :sweat_smile: right now, and I do have plans of benchmarking the revamped code on standard datasets.
Please feel free to shoot me an email if you still need the model.

**Comment by guuske31** [comment]
Hello @akanimax 
Thank you very much for your reply.
However, I am not anymore using this code.
So it is unnecessary to do it for me.
Still thank you very much for your reply.

Kind Regards,
Guus
