### ISSUE TITLE
Calculating fan_in for EqualizedConvTranspose2d 

### ISSUE THREAD

**Issue by srihari-humbarwadi** [akanimax/pro_gan_pytorch#52]
Is there a particular reason for using `fan_in = self.in_channels` for `EqualizedConvTranspose2d` in
https://github.com/akanimax/pro_gan_pytorch/blob/e3d2341333500b4792d60b42af3719eb524a52ec/pro_gan_pytorch/custom_layers.py#L110

compared to `fan_in = np.prod(self.kernel_size) * self.in_channels` for `EqualizedConv2d` in
https://github.com/akanimax/pro_gan_pytorch/blob/e3d2341333500b4792d60b42af3719eb524a52ec/pro_gan_pytorch/custom_layers.py#L62

**Comment by srihari-humbarwadi** [comment]
Answered here https://github.com/akanimax/pro_gan_pytorch/issues/44

**Comment by akanimax** [comment]
Glad to know that the issue was resolved. Please feel free to reopen if you still have any problem.
