### ISSUE TITLE
Missing LReLU activation after from_rgb conv layers

### ISSUE THREAD

**Issue by srihari-humbarwadi** [akanimax/pro_gan_pytorch#53]
Correct me if i am wrong, but are we supposed to apply an LReLU activation after the from_rgb  1x1 conv?

Table from the Appendix of the paper
![image](https://user-images.githubusercontent.com/24864163/103421742-f40b0180-4bc3-11eb-96c7-a6239c5430e2.png)

Relevant code from this repository
https://github.com/akanimax/pro_gan_pytorch/blob/e3d2341333500b4792d60b42af3719eb524a52ec/pro_gan_pytorch/networks.py#L160-L167

https://github.com/akanimax/pro_gan_pytorch/blob/e3d2341333500b4792d60b42af3719eb524a52ec/pro_gan_pytorch/networks.py#L190-L194

@akanimax

**Comment by guuske31** [comment]
Hello,

[The paper of Karras et al.](https://arxiv.org/pdf/1710.10196.pdf) states in appendix A1 that in every layer afterwards leaky ReLu is used, except for the last layer that uses linear activation. So no leaky ReLu is used in the from_rgb layer.  
This is stated in the second paragraph in the second sentence of Appendix A1.
I hope this answers your question?
Or is this not what you meant? :|

Kind Regards,
Guus

**Comment by srihari-humbarwadi** [comment]
@guuske31 Yes, the paper does mention `We use leaky ReLU with leakiness 0.2 in all layers of both
networks, except for the last layer that uses linear activation`. Here is the figure for both networks
![image](https://user-images.githubusercontent.com/24864163/103514961-bb08b080-4e93-11eb-955f-ecd1626e2d2a.png)
I think when the author says `except for the last layer that uses linear activation`, he is talking about the layers marked in yellow. That is not what I was asking, I was trying to understand the `conv 1x1` layered marked in blue, the author does seem to have mentioned an `LReLU` activation for it!

**Comment by guuske31** [comment]
Aah okay. Sorry my mistake.
But indeed. I was looking at the same section in the code and what you are mentioning is correct, no activation at all is taken after the Conv from rgb layer except for the avg pool 2d. 
So far as I can see you are correct.

**Comment by akanimax** [comment]
@srihari-humbarwadi, @guuske31,
Indeed you are right. The official TF implementation also applies a `LeakyRelu` in the `from_rgb` block ([here](https://github.com/tkarras/progressive_growing_of_gans/blob/master/networks.py#L261)).
https://github.com/akanimax/pro_gan_pytorch/blob/e3d2341333500b4792d60b42af3719eb524a52ec/pro_gan_pytorch/networks.py#L160-L167
A simple patch could be replacing the `ConvBlock` with a `Sequential(ConvBlock(...), LeakyReLU())`. Would you like to open a PR? It would be super helpful.
