### ISSUE TITLE
Output size

### ISSUE THREAD

**Issue by minxdragon** [akanimax/pro_gan_pytorch#55]
Hi @akanimax 
Is there anywhere that the output size of generated samples is specified? can I increase it at all?
Thanks!

**Comment by akanimax** [comment]
Hey,
Changing the [depth](https://github.com/akanimax/pro_gan_pytorch/blob/master/samples/train.py#L162) of the network produces higher resolution images. Note that you can only increase the sizes of the generated samples in powers of 2 (akin to mip-maps). And, you do need to retrain the network on this new higher resolution.

**Comment by minxdragon** [comment]
thank you!

**Comment by minxdragon** [comment]
hmm, whichever depth size I try I get _AssertionError: batch_sizes are not compatible with depth._ 
do I need to change the Batch_sizes as well? I'm trying every power of 2 I can think of!

**Comment by akanimax** [comment]
Oh yeah, you do need to change all the progressive growing `parameters` to be compatible with the chosen depth. `batch_sizes` is indeed one of them. Afair, the other two should be `epochs` and `fade-in_percentages`. You don't need to change the values there, but just make sure that these list sizes are equal to the queried depth.

**Comment by dhawan98** [comment]
What would be a good combination of depths and batch_sizes?

**Comment by akanimax** [comment]
Also: #57
Please refer to the Progressive growing of GANs paper for the hyperparameters to be used with the specific datasets. Afair, CIFAR-10 is indeed one of the benchmarks. 

Closing this issue for now.
