### ISSUE TITLE
Training the model

### ISSUE THREAD

**Issue by dhawan98** [akanimax/pro_gan_pytorch#56]
Is there a way I can train the model?
I used the code as it is and also the example mentioned in the readme.
You have mentioned a pg.ConditionalProGAN() in that CIFAR example. I could not find the mentioned function in the code.
Am I missing something?

**Comment by akanimax** [comment]
Hey,

The current version of the package doesn't support conditional variants of ProGANs. I never got around to including these features in the v3.0 line. Nevertheless, you can still use the package in the conditional generation setting with any kind of spatial data. 
Or, you could checkout a previous version and use the ConditionalProGAN from there. 
Hope this helps.
