### ISSUE TITLE
Can I generate a class-specific image using your code?

### ISSUE THREAD

**Issue by prash030** [akanimax/pro_gan_pytorch#6]
Hello @akanimax 
Thanks a lot for your implementation of Progressive Growing GANs!

I have a question: I understand that you are training the images based on classes. So, when testing, how do I specify the class label to the generator so that I can obtain an image of that class? 

Thanks in advance!

Edit: As a follow-up I am also curious about the author's paper where they use LSUN dataset. The paper does not get into details of how they did class-specific training but they have shown examples of images generated with class labels (eg. bedroom). Any insights on this would be much appreciated! Thanks.

**Comment by akanimax** [comment]
Hi @cardyfib,

I haven't tested the conditional Progessive GAN in this code -> [Conditional Pro GAN](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch/PRO_GAN.py#L464) yet. Please refer to the examples here -> [Examples](https://github.com/akanimax/pro_gan_pytorch-examples) for Unconditional Generation.
You can try using the **Conditional Pro GAN** in this package and let me know. My code uses the concatenation based conditional discrimination. However, if you are specifically interested in Conditional generation, then [Miyato et al.](https://arxiv.org/pdf/1802.05637.pdf) is the current SOTA for it. You can use the projection mechanism from this paper for your use. If you do end up using it, feel free to open PR here. Hope this helps.

Cheers :beers:!
@akanimax

**Comment by prash030** [comment]
That helps! Thanks for your response
