### ISSUE TITLE
not "pip install pro-gan-path" but "pip install pro-gan-pth"

### ISSUE THREAD

**Issue by earsonlau** [akanimax/pro_gan_pytorch#60]
😄

**Comment by akanimax** [comment]
Thanks for pointing out :smile:. 
fixed in [97a5b4503045e07ffaf4d41d88d9cc11706d26f0](https://github.com/akanimax/pro_gan_pytorch/commit/97a5b4503045e07ffaf4d41d88d9cc11706d26f0).
