### ISSUE TITLE
pretained model

### ISSUE THREAD

**Issue by fededemo** [akanimax/pro_gan_pytorch#68]
Hi @akanimax! Great work, really. Is it possible to train the model on a large dataset and then use the trained weights as a pretraining step for another one? Thanks for your help

**Comment by akanimax** [comment]
Hi @fededemo,
Thanks for the kind words :smile:. 
Doing transfer learning on GANs requires the original to be trained on a large and diverse dataset. I believe fine-tuning models trained on ImageNet (BigGAN, StyleGANXL) or the latest and the greatest GIGA-GAN trained on LAION would yield good results when fine-tuned on other datasets.

**Comment by fededemo** [comment]
Hi @akanimax! 
Thanks for your answer. I’m agree with you but my question it’s more about how can I do that with your code? 
It would be really great for me knowing it.
Thanks again

**Comment by akanimax** [comment]
Ah I see. No, unfortunately we don't have any models on ImageNet, so it's not possible with this code :frowning_face:.

**Comment by fededemo** [comment]
But if I have one, can I do it? We re planning to train one with Chest X ray and after, fine tuning it with other x ray small datasets to do some kind of “data augmentation”.
Thanks for your help.

**Comment by fededemo** [comment]
We have that big x ray dataset and our idea is to train the network from scratch with it, using your code, for a long time. Then use that pretrain to do fine tuning, again with your code,on another much smaller dataset with some rare diseases. We will like to know if it's possible using your code?

**Comment by akanimax** [comment]
Right I see. There isn't an option for resuming from a checkpoint in the training_script right now. But, all the information that is needed to do so is in the checkpoints ([checkpoint saving code](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch/gan.py#L241)). 

Adding resume functionality to the training script is easy, you can check how [generator loading](https://github.com/akanimax/pro_gan_pytorch/blob/8f892f64f62a5d7709547f22dc729b949c9a4c65/pro_gan_pytorch/networks.py#L228) is done for the latent_interpolation script.

**Comment by akanimax** [comment]
I can try to add this option to the `training_script` over the weekend.

**Comment by fededemo** [comment]
That would be great for us. Thanks again mate for your work and even more, for your help! 🥇

**Comment by fededemo** [comment]
Hi @akanimax!
 
@mauricio-repetto and I have been working on a potential solution to enable the retraining feature for your work. If you let us, we would like to submit a PR that includes modifications to [networks.py](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch/networks.py), [train.py](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch_scripts/train.py), and updates to the `README` documentation.

Thank you!

**Comment by fededemo** [comment]
Hi @akanimax!

@mauricio-repetto and I have been working on a potential solution to enable the retraining feature for your work. If you let us, we would like to submit a PR that includes modifications to [networks.py](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch/networks.py), [train.py](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch_scripts/train.py), and updates to the README documentation.

Thank you!

**Comment by akanimax** [comment]
Yeah sure, please feel free to open a PR. I'll go through it.

**Comment by fededemo** [comment]
Hi! I think that we may need access in order to push a new branch, its correct? Thanks!

**Comment by akanimax** [comment]
Hey, so to keep things inline with previous contributions, please use the usual fork->implement->pr method.

**Comment by fededemo** [comment]
HI! we just did it in: https://github.com/akanimax/pro_gan_pytorch/pull/69.
thanks!
