### ISSUE TITLE
implementation of MinibatchStdDev

### ISSUE THREAD

**Issue by SaoYan** [akanimax/pro_gan_pytorch#9]
The official implementation is [here](https://github.com/tkarras/progressive_growing_of_gans/blob/master/networks.py#L127).

1. It seems that in [your implementation](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch/CustomLayers.py#L273) there are multiple options, which don't exist in the official code. May I ask why?

2. Your default option is "all", which points to [this line](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch/CustomLayers.py#L311). However, the size of vals here is 1x1xHxW, that is you keep the spatial dimension. But according to both the paper and the official code, vals should be one single value (the average over all channels and pixels).

3. In your option "group", the code is actually not correct.
```
vals = vals.view(self.n, self.shape[1] / self.n, self.shape[2], self.shape[3])
vals = th.mean(vals, 0, keepdim=True).view(1, self.n, 1, 1)
```
The size of tensors would be incompatible.

**Comment by akanimax** [comment]
Please check the latest commit. I have made many changes..

Thank you
